contracts/Schelling4/StakeManager.sol, contracts/Schelling4/VoteManager.sol, test/StakeManager.js
Natspec comments and assert testing on the contracts
=> Sch4 tests

migrations/2_deploy.js, truffle-config.js
Changes to truffle-config.js and 2_deploy.js files
=> GasLimit and Migration change

contracts/SchellingCoin.sol
Closes #30 
Initial supply changed to 1 billion
=> change initial supply

contracts/Core/BlockManager.sol, test/BlockManager.js
=> fix duplicate block proposal

contracts/SchellingCoin.sol, package-lock.json, package.json, test/VoteManager.js, truffle-config.js
=> Increase Test coverage: voteManager

contracts/SchellingCoin.sol, test/BlockManager.js
=> Increase Test coverage: BlockManager

.gitignore, .solcover.js, README.md, package-lock.json, package.json, truffle-config.js
Hello Guys,
Solidity-Coverage integrated as required in issue https://github.com/razor-network/contracts/issues/36 <br/>
**For test coverage,**<br/> 
`npm install --save-dev solidity-coverage`<br/>
`npm run coverage` 
**Had to create new testNetwork in config due to following bug**
**Or refer**
https://github.com/trufflesuite/truffle/issues/2688#issuecomment-736639231
Thanks
=> Solidity coverage integrated

test/BlockManager.js
Testcase for https://github.com/razor-network/contracts/issues/6 added
=> Testcase for Issue#6 added - Dispute in Batches

contracts/Core/BlockManager.sol, contracts/Core/IBlockManager.sol, contracts/Core/VoteManager.sol
As Required in Issue https://github.com/razor-network/contracts/issues/9 
1. Added getNumProposedBlocks in IBlockManager Interface.
2. Added Switch in Vote Manager confirm block only when block in previous epoch has not been confirmed and if previous epoch do have proposed blocks
3. Removed Redundant switch from BlockManager due to 2
Thanks 👍
=> Optimization : Switch for Confirm Block in commit

contracts/Bridge.sol, contracts/Core/ACL.sol, contracts/Core/BlockManager.sol, contracts/Core/BlockStorage.sol, contracts/Core/IBlockManager.sol, contracts/Core/IJobManager.sol, contracts/Core/IStakeManager.sol, contracts/Core/IStateManager.sol, contracts/Core/IVoteManager.sol, contracts/Core/JobManager.sol, contracts/Core/JobStorage.sol, contracts/Core/StakeManager.sol, contracts/Core/StakeStorage.sol, contracts/Core/StateManager.sol, contracts/Core/Utils.sol, contracts/Core/VoteManager.sol, contracts/Core/VoteStorage.sol, contracts/Delegator.sol, contracts/Faucet.sol, contracts/IDelegator.sol, contracts/SchellingCoin.sol, contracts/lib/Constants.sol, contracts/lib/Random.sol, contracts/lib/Structs.sol, hardhat.config.js, package-lock.json, package.json
Removed Safemath.sol
Changed "now" keyword to "block.timestamp"
Changed path for oppenzeppelin/merkle.js
removed pragma ABI encoder
Changed openzeppelin-contracts to @openzeppelin/contracts_0.4.0
=> updated contract compiler version to v0.8.0 & removed unused dependencies from package.json

scripts/deploy.sh
Replaced openzeppelin-solidity to @openzeppelin
=> updated Deploy.sh

contracts/Core/ACL.sol, contracts/Core/BlockManager.sol, contracts/Core/BlockStorage.sol, contracts/Core/IBlockManager.sol, contracts/Core/IJobManager.sol, contracts/Core/IStakeManager.sol, contracts/Core/IStateManager.sol, contracts/Core/IVoteManager.sol, contracts/Core/JobManager.sol, contracts/Core/JobStorage.sol, contracts/Core/StakeManager.sol, contracts/Core/StakeStorage.sol, contracts/Core/StateManager.sol, contracts/Core/Utils.sol, contracts/Core/VoteManager.sol, contracts/Core/VoteStorage.sol, contracts/Delegator.sol, contracts/Faucet.sol, contracts/IDelegator.sol, contracts/SchellingCoin.sol, contracts/lib/Constants.sol, contracts/lib/Random.sol, contracts/lib/Structs.sol
Added **// SPDX-License-Identifier: UNLICENSED** in all the contracts
=> Added license and Solved warnings

migrations/src/postDeploymentSetup.js
fixed adding of minters in `postDeploymentSetup` migration script.
=> fixed adding of minters in `postDeploymentSetup` migration script.

hardhat.config.js
Updated solidity version to 0.8.4
fixes #132
=> Upgraded Solidity Version to 0.8.4

migrations/src/postDeploymentSetup.js
Replaced getAssetcreatorHash with getAssetModifierHash fixes #192
=> Replaced getAssetcreatorHash with getAssetModifierHash

contracts/Core/Parameters.sol, contracts/Core/RewardManager.sol, contracts/Core/interface/IParameters.sol, test/BlockManager.js, test/VoteManager.js
Fixes #152
Added a gov param as "percentSlashPenalty" by which we can decide and update how much percentage of the staker should be slashed and updated the slash function accordingly.
=> Made Slashing Penalty a Governance Parameter

hardhat.config.js
=> updated solidity version to 0.8.6

migrations/src/postDeploymentSetup.js
=> Fixes AssetModifier migration bug

contracts/Core/Parameters.sol, contracts/Core/StakeManager.sol, contracts/Core/interface/IParameters.sol, contracts/Core/interface/IStakeManager.sol, contracts/Core/storage/RewardStorage.sol, test/StakeManager.js
=> add escape hatch and tests

contracts/Core/StakeManager.sol
=> Add address for unstake and withdraw events

contracts/Core/BlockManager.sol, contracts/Core/RewardManager.sol, contracts/Core/VoteManager.sol, contracts/Delegator.sol
=> change public -> external fixes #235

contracts/Core/ACL.sol, package-lock.json, package.json, test/ACL.js, test/BlockManager.js, test/Parameters.js, test/StakeManager.js, test/VoteManager.js
=> upgarde openZeppelin to 4.2.0

.circleci/config.yml, README.md, package.json
=> Circleci project setup

test/StakeManager.js
fixes #229 
All the positive cases were already being tested 
Added test cases at the appropriate positions to check for the negative tests 
Also checked all the combinations were being handled 
Added  6 more test cases to cover pausable contract
=> Added more test cases to cover pausable contracts

contracts/Core/BlockManager.sol
Since, we have decided to check the gas amount on client side, I have removed the gas check
=> Removed Gascheck

contracts/Core/StakeManager.sol
=> Added Event for delegation Accepted

contracts/Core/BlockManager.sol, contracts/Core/Parameters.sol, contracts/Core/RewardManager.sol, contracts/Core/VoteManager.sol, contracts/Core/interface/IAssetManager.sol, contracts/Core/interface/IParameters.sol, contracts/Core/interface/IVoteManager.sol, contracts/lib/Structs.sol, migrations/src/7_deploy_vote_manager.js, migrations/src/postDeploymentSetup.js, test/BlockManager.js, test/StakeManager.js, test/VoteManager.js, test/helpers/testSetup.js, test/helpers/utils.js
This reverts commit 034b303a4174ae846e0ed21b013b90c68bd41715.
Reverts Assign Assets Randomly PR https://github.com/razor-network/contracts/pull/206
=> Revert "Assign Assets Randomly (#206)"

test/Parameters.js
fixes #272 
Modified test case added some params that required assertions
1) Mythx tests failing
2) On checking coverage (https://coveralls.io/builds/41878754/source?filename=contracts%2FCore%2FParameters.sol) 
&
(https://app.circleci.com/pipelines/github/razor-network/contracts/72/workflows/f8897f25-ffb5-4120-908d-cf457b0ea36d/jobs/257?invite=true#step-102-267) is 100% but according to coveralls it remains same is it an issue ?
=> Modified test case to increase coverage for parameters

test/VoteManager.js
fixes #270 
1)  Added some test cases to increase the coverage of statements and functions 
2)  Changed one line which was already in test case  (https://github.com/razor-network/contracts/pull/271/files#diff-f683c8d5b95777f9e626d97eb2b74a82ffe9f58b93fe5f4a6a704f90885120baL163) 
Reason : Sometimes it was passing and some times failing due to which it makes another 2 3 test cases fail , now it is fixed
Everything is working fine locally but tests are not passing during checks here (reason : unknown ).
=> Added test cases to increase coverage for votemanager

contracts/Core/Parameters.sol
=> Added event for all setters

test/StakeManager.js
Fixes #202 
This PR adds a test case that proves that conversion would work for 1RZR if totalSupply of sRZR is 2000 and the current stake is 1000 RZR
Calculation: https://docs.google.com/spreadsheets/d/1nEzJgNQRYibkJbM3JxdWgCccJYncV_zkuTyOs81G_AU/edit?usp=sharing
=> Test added for Issue #202 

migrations/src/postDeploymentSetup.js
=> Fixed Migration bug

test/VoteManager.js
Fixes #315 
Added test cases to increase coverage on votemanager
coverage => 100
=> Increases coverage on votemanager

test/BlockManager.js
Wrote a test case when staker cannot propose due to stake below mistake
fixes #319
=> Added testcase, staker cannot propose when stake is below minstake

test/AssetManager.js
Fixes #313 
Added test cases to increase the coverage
Also changed some existing assertions (to increase function call coverage)
Coverage => 100
=> Increased coverage on AssetManager

test/VoteManager.js
Fixes #326 
Increases coverage on Initializable file.
=> Checked that contracts are initialized only once

contracts/Core/RewardManager.sol, contracts/Core/StakeManager.sol, contracts/lib/Structs.sol, test/StakeManager.js, test/VoteManager.js
Fixes #311 
Actually this => "Staker can stake small amount and get away without inactivity penalty"  isn't happening 
only thing is as discussed the name of property "epochStaked" of staker should be changed to "epochFirstStaked" to remove any confusion.
=> Staker can stake small amount and get away without inactivity penalty

.gitignore, README.md, package-lock.json, package.json, scripts/gasAnalyze.js
=> Gasreport across various networks

test/BlockManager.js
=> negative test cases for finalize dispute

test/BlockManager.js
#350 Wrote testcases for ClaimBlockReward Function, covered all the require statements in the function.
=> Added testcases for ClaimBlockReward

contracts/Core/AssetManager.sol, test/ACL.js, test/AssetManager.js
Fixes https://github.com/razor-network/contracts/issues/309
Asset Modifier Role can update aggregation method and power of collection.
=> Update Collection added

test/AssetManager.js
=> Added testcases for updateCollection

contracts/Core/AssetManager.sol, contracts/Core/BlockManager.sol, contracts/Core/Parameters.sol, contracts/Core/StateManager.sol, contracts/Core/interface/IAssetManager.sol, contracts/Core/storage/AssetStorage.sol, contracts/lib/Structs.sol, test/ACL.js, test/AssetManager.js, test/BlockManager.js, test/StakeManager.js, test/VoteManager.js
Fixes #105 
Details of active assets in #297
=> Block Proposal Bug Fix

contracts/Core/VoteManager.sol, test/StakeManager.js
Fixes #369 
First commit has a failing test case, which proves issue exist
The second commit solves the issue
Please review and merge this soon if this is applicable, as its blocking PR for #366 due to failing testcase
=> Corrected the Inequality for minstake in reveal

contracts/Core/StakeManager.sol, test/StakeManager.js
=> Staker should be allowed to set comission before accepting delegation.

test/AssetManager.js, test/Parameters.js, test/StakeManager.js
Added test cases in parameters , asset manager and stake manager to increase the coverage
#350
=> added test cases to increase coverage

package-lock.json, package.json
There was an issue with the old dependency of hardhat, hence have updated it
Have updated all other dependencies to the latest as well
=> Updated All Dependencies

migrations/src/postDeploymentSetup.js
Fixes #409 
Signed-off-by: Ashish Mishra <ashish10677@gmail.com>
=> Change stakeManager to assetManager in postDeploymentSetup.

contracts/Core/StakeManager.sol
=> Added msg.sender for events

contracts/Core/StakeManager.sol, scripts/gasCompare.js
Added Event for Reset Lock and Added the Difference Column for GasCheckBot 
fixes #424 fixes #363
=> Added event for reset lock

scripts/gasCompare.js
fixes #431 
Only shows methods for which number of calls > 0
=> Ignored the case when GasData is not available and removed brackets.

contracts/Core/VoteManager.sol, scripts/gasCompare.js
=> Gas Check should happen on maximum value rather median value

test/Parameters.js
Some new pararmetres were added in parameters.sol so I have tested them to increase the coverage.
=> Added test cases for newly added parameters in parameters.sol

contracts/Core/RewardManager.sol, contracts/Core/StakeManager.sol, contracts/Core/interface/IStakeManager.sol, contracts/Core/storage/Constants.sol, migrations/src/postDeploymentSetup.js, test/ACL.js, test/StakeManager.js
=> Patch for v0.1.6

contracts/Core/AssetManager.sol, contracts/Core/interface/IAssetManager.sol, contracts/Delegator.sol, contracts/lib/Structs.sol, test/ACL.js, test/AssetManager.js
In this PR, I have removed the status variable for job. Now only collections will have active Status. 
Renamed function names setAssetStatus --> setCollectionStatus , getActiveStatus --> getCollectionStatus
fixes #449
=> removed Job Status : Now Job will not have any activity Status.

contracts/Core/BlockManager.sol
https://github.com/razor-network/contracts/pull/461#issuecomment-925266283
=> Added a comment to ignore slither warning at L183

hardhat.config.js
added a automine configuration to hardhat.config.js
=> hardhat-automine

contracts/Core/StakeManager.sol
We did this modification in the patch for 0.1.6 version but it was not done for 0.1.7 version of contracts. hence I have done this modification. It fixes #484
=> added amount in delegator event

contracts/Core/AssetManager.sol, contracts/Core/BlockManager.sol, contracts/Core/RewardManager.sol, contracts/Core/StakeManager.sol, contracts/Core/StateManager.sol, contracts/Delegator.sol, contracts/randomNumber/RandomNoManager.sol, test/StakeManager.js, test/VoteManager.js
fixes #529 
https://blog.polymath.network/solidity-tips-and-tricks-to-save-gas-and-reduce-bytecode-size-c44580b218e6
=> Applicable functions made internal

contracts/Core/BlockManager.sol, contracts/Core/StakeManager.sol, contracts/Core/parameters/child/StakeManagerParams.sol, contracts/Core/parameters/child/VoteManagerParams.sol, contracts/Core/storage/Constants.sol, contracts/Core/storage/StakeStorage.sol, contracts/lib/Structs.sol
Fixes #433 
Have went through the code and packed wherever possible.
Please let me know if there is further any poss to pack.
=> Applicable variables packed 

contracts/Core/StakeManager.sol
=> added amount in Staked event

contracts/Core/AssetManager.sol, contracts/Core/BlockManager.sol, contracts/Core/RewardManager.sol, contracts/Core/VoteManager.sol, contracts/Core/interface/IAssetManager.sol, contracts/Core/interface/IVoteManager.sol, contracts/Core/storage/AssetStorage.sol, contracts/Core/storage/BlockStorage.sol, contracts/Delegator.sol, contracts/IDelegator.sol, contracts/lib/Structs.sol
=> fix: assetId, blockId made uint16, uint32 respectively

contracts/Core/RewardManager.sol, contracts/Core/StakeManager.sol, contracts/Core/interface/IStakeManager.sol, contracts/Core/storage/Constants.sol, test/BlockManager.js
fixes #590 
fixes #599 
fixes #587
=> AgeChanged reason added

.circleci/config.yml, package.json, scenarios/scenarios.js
=> tests and scenarios separated

contracts/Core/StakeManager.sol
- event has been added for commission change with parameter as stakerId and commission.
fixes #608
=> event added for commission change

contracts/Core/StakeManager.sol
-extendLock event added
-emit stakerId from resetLock
fixes #615
=> extendLock event added

scenarios/scenarios.js
=> new scenarios added

contracts/Core/AssetManager.sol, contracts/Core/RewardManager.sol, contracts/Core/interface/IAssetManager.sol, contracts/Core/parameters/Governance.sol, contracts/Core/parameters/child/AssetManagerParams.sol, contracts/Core/parameters/child/RewardManagerParams.sol, contracts/Core/parameters/interfaces/IAssetManagerParams.sol, contracts/Core/parameters/interfaces/IRewardManagerParams.sol, contracts/lib/Structs.sol, scenarios/scenarios.js, test/ACL.js, test/AssetManager.js, test/BlockManager.js, test/Delegator.js, test/Governance.js, test/StakeManager.js, test/VoteManager.js, test/helpers/testSetup.js
=> Tolerance added

contracts/Core/BlockManager.sol, contracts/Core/RewardManager.sol, contracts/Core/VoteManager.sol, contracts/Core/interface/IVoteManager.sol, contracts/Core/storage/VoteStorage.sol, contracts/lib/Structs.sol, scenarios/scenarios.js, test/BlockManager.js, test/Delegator.js, test/RandomNoManager.js, test/StakeManager.js, test/VoteManager.js, test/helpers/utils.js
=> Consensus Improvements

migrations/src/postDeploymentSetup.js, package.json
hotfix for postDeploymentScript
=> V0.2.0 patch1

contracts/Core/parameters/Governance.sol
=> V0.2.0 patch2

contracts/Core/StakeManager.sol, scenarios/scenarios.js, test/StakeManager.js
=> randao bug fix

.circleci/config.yml
Configured Cirlce-CI to execute scenarios along with test cases.
Fixes [600](https://github.com/razor-network/contracts/issues/600)
=> Configured scenarios in CI

contracts/Core/BlockManager.sol, contracts/Core/StakeManager.sol, contracts/Core/VoteManager.sol, contracts/Core/interface/IStakeManager.sol
=> bounty id now emitted

hardhat.config.js
Some tests fails due to timeout issues.
Set the mocha timeout to 30000
Fixes #686
=> Increased timout for tests globally

test/VoteManager.js
Added tests to increase coverage for vote manager #685
=> Increased Coverage on VoteManager

README.md
Release v0.3.0-rc2
Update readme
=> Release v0.3.0-rc2

test/CollectionManager.js
Added Test case to increase coverage on CollectionManager and this also in turn increased coverage no delegator.sol
=> Increased Coverage on CollectionManager and Delegator

contracts/Core/BlockManager.sol, docs/BlockStorage.md, docs/Delegator.md, docs/IBlockManager.md, docs/IDelegator.md, docs/IStakedToken.md, docs/IStakedTokenFactory.md, docs/IVoteManager.md, docs/StakeManager.md, docs/StakedToken.md, docs/StakedTokenFactory.md, docs/VoteManager.md, docs/VoteStorage.md
=> fix: removed require statement from BlockManager

contracts/Core/VoteManager.sol
https://app.circleci.com/pipelines/github/razor-network/contracts/1306/workflows/a4733fe0-a7bc-4478-a066-a7728abc3ec2/jobs/8071
=> fix: optmized for calls in loop : slither warning

contracts/Core/BlockManager.sol
Fixes https://github.com/razor-network/contracts/issues/749
=> chore: emit ids for BlockEvents 

contracts/Core/BlockManager.sol, test/AssignCollectionsRandomly.js
=> fix: dispute 'disputeCollectionIdShouldBePresent()' is successful if empty array is passed

contracts/Core/StateManager.sol
=> fix: fixed overflow issue

contracts/Core/BlockManager.sol, test/AssignCollectionsRandomly.js, test/BlockManager.js, test/helpers/InternalEngine.js
Fixes #759 
1) Added ids.length == medians.length check in propose function
2) Negative test case written for that
3) Small fix in Internal Engine file
=> feat: added require length check in propose

contracts/Core/RewardManager.sol, test/StakeManager.js
=> fix: stakerReward being updated properly

commitlint.config.js, yarn.lock
BREAKING CHANGE: v1.0.0 release.
=> Release: v1.0.0

CHANGELOG.md, commitlint.config.js, package.json
=> BREAKING CHANGE: Release

contracts/Core/BlockManager.sol, contracts/Core/CollectionManager.sol, contracts/Core/StakeManager.sol, contracts/Core/StateManager.sol, contracts/randomNumber/RandomNoManager.sol
=> feat: made getstate and getepoch functions public

contracts/Core/BlockManager.sol, contracts/Core/CollectionManager.sol, contracts/Core/RewardManager.sol, contracts/Core/VoteManager.sol, contracts/Core/interface/IBlockManager.sol, contracts/Core/interface/ICollectionManager.sol, contracts/Core/interface/IVoteManager.sol, contracts/Core/storage/BlockStorage.sol, contracts/Core/storage/VoteStorage.sol, contracts/Delegator.sol, contracts/IDelegator.sol, contracts/lib/Structs.sol, test/VoteManager.js, test/helpers/utils.js
=> fix: votes and medians datatype changed to uint256

hardhat.config.js
=> feat: added skale-v2 support in hardhat config

contracts/Core/BlockManager.sol, contracts/Core/CollectionManager.sol, contracts/Core/StakeManager.sol, contracts/Core/VoteManager.sol, contracts/Core/parameters/Governance.sol
=> fix: indexed event parameters

contracts/Core/BlockManager.sol, contracts/Core/StakeManager.sol, contracts/Core/VoteManager.sol
=> feat: add more events

contracts/Core/StakeManager.sol, test/StakeManager.js
=> fix: initiateWithdraw bug fix

contracts/Core/StakeManager.sol, test/StakeManager.js
=> fix: staker should not be able to delegate to themself

contracts/Core/StakeManager.sol, test/StakeManager.js
=> fix: checks increased in unstake flow

contracts/Core/StakeManager.sol, contracts/Core/parameters/Governance.sol, contracts/Core/parameters/child/StakeManagerParams.sol, contracts/Core/parameters/interfaces/IStakeManagerParams.sol, scenarios/scenarios.js, test/Governance.js, test/StakeManager.js
=> fix: precision on resetUnstakeLockPenalty increased

contracts/Core/CollectionManager.sol, contracts/Core/StakeManager.sol, contracts/Core/VoteManager.sol, contracts/Core/interface/IRewardManager.sol
=> chore: removing warnings and todos

.env.ci, .env.tpl, migrations/src/postDeploymentSetup.js
=> fix: transfer razor only during testnet deployment

contracts/Core/BlockManager.sol
=> fix: sortedValues datatype fix

contracts/Core/CollectionManager.sol, test/CollectionManager.js
=> fix: jobIds existence checked while creation and updation

migrations/src/postDeploymentSetup.js
=> fix: initiliaze roles before initializing contracts

contracts/Core/CollectionManager.sol, contracts/Core/RewardManager.sol, contracts/Core/VoteManager.sol, test/VoteManager.js
=> fix: collection tolerance retrival bug fixed

contracts/Core/RewardManager.sol, contracts/Core/parameters/Governance.sol, contracts/Core/parameters/child/RewardManagerParams.sol, contracts/Core/parameters/interfaces/IRewardManagerParams.sol, test/Governance.js, test/StakeManager.js
=> feat: add `penaltyAgeNotRevealNum` for giving inactivity penalties

test/BlockManager.js, test/helpers/utils.js
=> chore: added tests for isElectedProposer (second false if block)

contracts/Core/RewardManager.sol, contracts/Core/StakeManager.sol, contracts/Core/interface/IStakeManager.sol, test/StakeManager.js
=> fix: rename setStakerStakerReward and remove _isStakerActive

contracts/Core/CollectionManager.sol, contracts/Core/interface/ICollectionManager.sol, test/CollectionManager.js, test/helpers/utils.js
=> chore: test getDepth through external function

contracts/Core/BlockManager.sol
=> feat: added `claimBlockReward` event

contracts/Core/parameters/Governance.sol, contracts/Core/parameters/child/RewardManagerParams.sol, contracts/Core/parameters/child/StakeManagerParams.sol, contracts/Core/parameters/interfaces/IStakeManagerParams.sol, test/Governance.js, test/StakeManager.js
=> fix: minor fixes and change data type of lock and initiation period

test/BlockManager.js
=> chore: test added to make sure collectionIdToLeafIdRegistry/LastEpoch assignments work fine

contracts/Core/VoteManager.sol, test/VoteManager.js, test/helpers/InternalEngine.js, test/helpers/utils.js
=> fix: redundancy on secret calculation removed

contracts/Core/storage/Constants.sol, test/AssignCollectionsRandomly.js, test/helpers/constants.js
=> feat: epochLength changed to 20 mins

package.json
This reverts commit 664e5a2defced093b46425fe49a86dafb0ee05ed.
=> Revert "fix: code coverage fix (#959)"

package.json
=> fix: code coverage fix

contracts/Core/BlockManager.sol, contracts/Core/CollectionManager.sol, contracts/Core/StakeManager.sol, contracts/Core/VoteManager.sol, contracts/randomNumber/RandomNoManager.sol
=> chore: index epoch in events

scripts/gasAnalyze.js
=> fix: gas analyzer fixed

test/Delegator.js
=> fix: delegator tests independent

test/AssignCollectionsRandomly.js
=> feat: assign collections randomly tests optimized

test/AssignCollectionsRandomly.js, test/BlockManager.js
=> fix: block manager tests optimizations

test/StakeManager.js, test/VoteManager.js
=> fix: stake manager test optimizations

contracts/Core/BlockManager.sol, contracts/Core/CollectionManager.sol, contracts/Core/RewardManager.sol, contracts/Core/VoteManager.sol, contracts/Core/interface/ICollectionManager.sol, contracts/Core/storage/CollectionStorage.sol, contracts/lib/Structs.sol, scenarios/scenarios.js, test/AssignCollectionsRandomly.js, test/BlockManager.js, test/BondManager.js, test/CollectionManager.js, test/Delegator.js, test/RandomNoManager.js, test/StakeManager.js, test/VoteManager.js, test/helpers/InternalEngine.js, test/helpers/utils.js
=> feat: storing votes and voteWeights with collectionid instead of leafid

contracts/Core/storage/Constants.sol, migrations/migrationHelpers.js
fixes #1000 
The Current epoch length is 1200s/20 mins and needs to be changed to 300s/5 mins for the upcoming release.
- Epoch length has been changed
- changes in the deployment script regarding fetching jobs and collections from datasources
=> feat: epoch length changed
