razor-network/oracle-contracts

- test/BlockManager.js
- test/StakeManager.js
- test/VoteManager.js
- test/helpers/functions.js
Allows us to mine to next Epoch or next state in the tests so no need to manually change contracts just for setting epoch and state.
> Adding mining functionality for epoch and state

- README.md
- test/ACL.js
- test/JobManager.js
**Tests written in ACL.js were inconsistent as they were async, made them sync by await
and added a new test case for Flexible Admin**
**Flexible Admin:** 👍 
The solution to Issue: To add the functionality of changing default admin in access control to ensure flexibility #39.
Openzeppelin Access control, already allows this functionality, so just needed to test if it's working properly in our case.
That's done now, its working fine.
Thanks!
> Tests Patch : Made them Sync by Await and added test for Flexible admin

- contracts/Core/StakeManager.sol
- contracts/Core/StakeStorage.sol
- contracts/lib/Constants.sol
- test/BlockReward.js
- test/VoteManager.js
Hi All,
As pointed out in https://github.com/razor-network/contracts/issues/66 we needed a decreasing block reward function.
The same has been implemented in this PR.
We have used the standard halving function.
Where we halve block reward after a specific interval (measured in no of blocks)
```
function _calculateBlockReward() private returns(uint256)
{
uint256 halvings = (block.number - genesisBlock) / Constants.halvingInterval();	
if(halvings > lastHalvings) {
lastBlockRewards = Constants.initialBlockReward() >>  halvings;
lastHalvings = halvings;
}
return lastBlockRewards	;		
}
```
**Please note that we will have to tune these constants (halvingInterval and Initial Block Rewards) as per tokenomics and deployment chain.**
As of now, I have kept _calculateBlockReward() as private but I …
> To Implement Block Reward Function | Halving

- contracts/SchellingCoin.sol
- test/ACL.js
- test/BlockManager.js
- test/JobManager.js
- test/SchellingCoin.js
- test/StakeManager.js
Fix - inheriting ACL contract in SchellingCoin contract instead of OZ's AccessControl contract, refactored few tests.
This PR closes issue #111
> inheriting ACL contract in SchellingCoin contract, refactored few tests

- contracts/lib/Constants.sol
- test/ACL.js
- test/helpers/constants.js
The blocktime for goerli is 15 seconds whereas for matic it's 2 seconds. The current epoch length is set according to the goerli but this epoch length doesn't work for matic. It does not sync with the states due to which transactions are reverted
in order to match Matic and goerli block time, I have changed the epoch length to 300
Fixes #139
> refactored_epoch_length_to_300

- contracts/Core/Parameters.sol
- contracts/Core/StakeManager.sol
- contracts/Core/interface/IParameters.sol
- test/Parameters.js
Fixes https://github.com/razor-network/contracts/issues/104
Hi Guys,
This is small PR.
Firstly grace period is defined as constant and fetched from there so in the future we can expose it as a governance parameter.
Secondly 
rather than passing "Current Epoch - Last Active", 
now we are passing "Current Epoch - Last Active-1" to calculateInactivePenalties()
Which actually represent no of inactive epochs
Please refer to issue https://github.com/razor-network/contracts/issues/104 for more details
**Please note
This doesn't change any earlier behavior, as confirmed by tests as well.**
Rather than having
X < 10
first, we went 
X-1 < 9
then
X-1 <=8
That's all!
Here X is Current Epoch - Last Active
Signed-off-by: abhishekvispute <abhivispute33@gmail.com>
> Fetching grace period from parameters and making its use readable

- contracts/SchellingCoin.sol
- test/SchellingCoin.js
Currently anyone can become minter or remove itself as minter which might lead to some security issues. Hence in order to resolve this I have added a restriction that only owner can add the Minter and remove the minter.
resolves #140
> Added restriction to Schelling Coin add Minter and Remove Minter

- .circleci/config.yml
test-results is stored if we use JUnit. Since we are not, it is not necessary.
> remove test-results from yaml

- contracts/Core/RewardManager.sol
We can inherit modifiers from Statemanger if we need to use it in any new method.  Currently no method in RewardManager uses both modifiers.
> Redundant code : CheckState And checkEpoch in rewardManager.sol

- contracts/Core/BlockManager.sol
- contracts/Core/RewardManager.sol
- contracts/Core/VoteManager.sol
- test/BlockManager.js
- test/VoteManager.js
Fixes #182 
VoteManager stores votes from 0..n-1 for assets with assetids 1 to n
It mainly impacted two functions
getVoteValue 
and 
giveSortedVotes
In both places, the user earlier had to pass assetid-1 as assetid to get the required results.
both have been solved by this PR.
now user don't have to pass -1, he passes from 1 to N only, we do -1 inside
please check tests to see how its changed
> Made assetId consistent | 1 to N throughout

- contracts/Core/AssetManager.sol
- contracts/lib/Structs.sol
- test/ACL.js
- test/AssetManager.js
Fixes #266 
With this addition 
We have added the required flexibility for reporting results. 
A new parameter called as power is added to job and collection.
In a job, power signifies how the staker should interpret and convert the value fetched from API 
in collection, power signifies how a staker should vote and how client should interpret the result 
for example lets take a collection A<>B
it has 2 jobs 
job 1 : value : 100 power : 2
job 2 : value : 100000 power : -1
staker when aggregate, aggregate it by expanding
100,00, 100,00
and propose w.r.t power of collection, let's say it is 2 
then a result of collection would be 
result: 100
power: 2
> Add Power to Job and Collections

- contracts/Core/StateManager.sol
Fixes #348 
Removed checkEpoch Modifier from  "stateManager.sol"  file as it was not being used anywhere.
> Removed checkEpoch Modifier from stateManager.sol

- contracts/Core/BlockManager.sol
- test/BlockManager.js
- test/helpers/utils.js
fixes #365 
First Commit :
First commit shows that there is inconsistecy in asset Id as the test case is failing being the same median for both the proposed blocks
Second Commit  :
In second commit inconsistecy is removed in finalize dispute and calc dispute data.
> Fixed inconsistency in assetId in finalize dispute and calc dispute data with test case

- contracts/Core/StateManager.sol
- contracts/mocks/InitializableMock.sol
- test/Initializable.js
#350
Here added thet test case for checking modifier Initializer.
Taken reference from OpenZeppelin. They have written a mock file which has function that uses modifier 'Initializer' & one more function initializeNested which also uses modifier 'initializer'.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/utils/Initializable.sol
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b9125001f0a1c44d596ca3a47536f1a467e3a29d/contracts/mocks/InitializableMock.sol
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b9125001f0a1c44d596ca3a47536f1a467e3a29d/test/utils/Initializable.test.js
> Test for modifier Initializer 

- contracts/Core/RewardManager.sol
- contracts/Core/StakeManager.sol
- contracts/Core/interface/IRewardManager.sol
- contracts/lib/Structs.sol
- test/StakeManager.js
Fixes #284 
Fixes #359 
> problem
> 
>     * can bypass inactivity penalty
>       -unstake() and withdraw() after inactivity since we are not checking inactivity there
> 
>     * after partial unstaking staker still cant participate
>       
>       * after returning after lock period he will get inactivity penalty
> 
> 
> solution 1
> 
>     * unstake() convert unstaked srzr to rzr and reduce from stake; add to lock 10000
> 
>     * withdraw() allow locked rzr to withdraw
> thisStaker.epochFirstStaked -> rename to thisStaker.epochLastUnstakedOrFirstStaked
> Inactivity bug

- contracts/Core/AssetManager.sol
- contracts/Core/StateManager.sol
- test/AssetManager.js
fixes #386 
The modifier name in state manager has been changed to notState form notCommitState and it has been now added in update collection.
> Changed modifier name and added it in update collection

- test/VoteManager.js
Fixes #413 
This is not an issue because if anyone calls snitch on any staker than the commitmentHash is set to zero for that staker.
(https://github.com/razor-network/contracts/blob/c248922e0e72e8c69a7df357e1eac17497afe3ab/contracts/Core/VoteManager.sol#L103) 
Now, if anyone calls snitch the second time on same staker than it will revert from here 
(https://github.com/razor-network/contracts/blob/c248922e0e72e8c69a7df357e1eac17497afe3ab/contracts/Core/VoteManager.sol#L101)
as require condition fails.
> Should not snitch more than once on any staker for same mal activity 

- contracts/Core/AssetManager.sol
- contracts/Core/interface/IAssetManager.sol
- contracts/Delegator.sol
- contracts/lib/Structs.sol
- test/ACL.js
- test/AssetManager.js
- test/BlockManager.js
- test/StakeManager.js
- test/VoteManager.js
Fixes #435 
With this PR we have added weights to job 
so now whenever the client proposes a median for collection  
they have to do weighted median
```
j1v*j1w + j2v*j2w + j2v*j2w ....
----------------------------------------
j1w + j2w + j3w...
j(i)v = value of ith job
j(i)w = weight of ith job
````
on setting the weight of the job, have kept condition of max 100,
it's true that value is added in the numerator as well as deno, so one can say there wont be an issue.
it's for setting up limit
lets say
I have assets with weights 30,40,90 as weights 
when you add a new asset in this collection you add it with considering 100 as max, so there is a defined limit
you cant add it with 900 or something, which would dilute other weights
> Added Weights for Jobs

- contracts/Core/Parameters.sol
- contracts/Core/StakeManager.sol
- contracts/Core/interface/IParameters.sol
- test/BlockManager.js
- test/VoteManager.js
Fixes #389 
Have made penalty divider customizable
Earlier it was 2
so slashPenalty/2 was awarded
now its slashPenalty * bountyNum / bountyDenom
have kept bountyNum = 500
bontyDenom = 10000
so at last its slashPenalty/20 , 5 %
from remaining 95% amount, 
```
95% amount * burnSlashNum/burnSlashDenom
```
is burned, remaining stays is contract
> Customised Bounty and Amount to be burned

- contracts/Core/StakeManager.sol
- test/StakeManager.js
Currently If staker wants to increase stake, staker needs to stake RZR tokens >= minStake. But now staker can stake any number of tokens untill amount + currentStake >= minStake.
Let Say staker A has currentStake = 990 RZR tokens, amount it want to stake is 10 RZR tokens, then staker can easily increase stake with 10 RZR tokens because it statisfies the condition. 
Fixes #459
> staker should be able to increase stake with n number of RZR token

- contracts/Core/BlockManager.sol
- contracts/Core/storage/BlockStorage.sol
- contracts/lib/Structs.sol
- test/BlockManager.js
Fixes #415 
Have introduced new variable called as blockIndexToBeConfirmed
It keeps track of best block index from sortedProposedBlockIds.
Every time some one calls finalizeDispute, we check if the one with blockIndexToBeConfirmed is disputed, if yes we find next best and assign it.
Its set as -1 if all blocks are disputed. that's why its int8.
> Finalize Dispute : Sorted Proposed Blocks Bug Fix

- contracts/Core/Parameters.sol
- contracts/Core/RewardManager.sol
- contracts/Core/StakeManager.sol
- contracts/Core/interface/IParameters.sol
- test/BlockManager.js
- test/Parameters.js
- test/StakeManager.js
- test/VoteManager.js
Fixes #460 
And following slither warning
```
StakeManager.slash(uint32,uint32,address) (contracts/Core/StakeManager.sol#289-316) performs a multiplication on the result of a division:
-slashPenaltyAmount = (_stake * parameters.slashPenaltyNum()) / parameters.slashPenaltyDenom() (contracts/Core/StakeManager.sol#295)
-bounty = (slashPenaltyAmount * parameters.bountyNum()) / parameters.bountyDenom() (contracts/Core/StakeManager.sol#298)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#divide-before-multiply
. analyzed (66 contracts with 73 detectors), 1 result(s) found
```
> Bounty and amount_to_be_burned calculated directly on stake and denominator for penalty calculation made common across

- contracts/Core/RewardManager.sol
- contracts/Core/storage/Constants.sol
Fixes #631 
Renamed VotingPenalty to VotingRewardOrPenalty.
Now for increase or decrease of age in both the cases 'VotingRewardOrPenalty' as a reason will be emitted in event.
> Rename VotingPenalty to VotingRewardOrPenalty

- contracts/Core/StakeManager.sol
- test/MerklePosAware.spec.js
- test/StakeManager.js
Added comments on all the erc20 functions that can't be negatively tested.
> test: increased Coverage on StakeManager and MerklePos

- scenarios/scenarios.js
- test/AssignCollectionsRandomly.js
- test/helpers/testHelpers.js
- test/helpers/utils.js
while its in buffer state it was returning -1
now here we cant do mineToNextState because its just a buffer state we need to wait till it it reaches to the window where we can vote
`while (Number(await getState()) !== 4) {
if (Number(await getState()) !== -1) {
await mineToNextState();
}
} `
so as per the current code if state == -1 we do nothing
This was causing while loop to go in infinte loop because everytime in getState we were calculating block timestamp based on the same block number since nothing was getting mined
` while (Number(await getState()) !== 4) {
if(await getState()=== -1){
await mineBlock();
}
else{
await mineToNextState();
}
} `
so I modified this method, that if state is -1 , we mine block, so that getState could come out of buffer state and transaction could happen.
> fix: fixed scenarios

- contracts/Core/StakeManager.sol
- contracts/Core/parameters/Governance.sol
- contracts/Core/parameters/child/CollectionManagerParams.sol
- contracts/Core/parameters/child/RewardManagerParams.sol
- contracts/Core/parameters/child/StakeManagerParams.sol
- contracts/Core/storage/Constants.sol
- test/Governance.js
fixes #748 
Done 
```
too many digits
require on trasnfer
```
NA 
```
costable states : 
slither is not asking to assign value only, then want to define it CONSTANT
```
https://github.com/crytic/slither/wiki/Detector-Documentation#state-variables-that-could-be-declared-constant
```
reeent no eth check 
we deducted its meaning incorrect last time, it doesn't say that eth is involved, its contrary
```
https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-1
> chore: slither warnings

- test/Governance.js
- test/StakeManager.js
Fixes #773 
blockReward set to 0 and the whole flow work accordingly.
inactivityPenalty given 0 and the whole flow work accordingly.
> test: blockReward and inactivityPenalty set to 0 for testing

- migrations/src/7_deploy_delegator.js
there was a check required for env file, if delegator address is not there then contracts should be deployed. fix #772
> fix: fixed delegator migration

- contracts/Core/CollectionManager.sol
- contracts/Core/RewardManager.sol
- contracts/Core/StakeManager.sol
- contracts/Core/StateManager.sol
- contracts/Core/VoteManager.sol
- contracts/Core/interface/IStakeManager.sol
> fix: updated and added comments on contracts

- .circleci/config.yml
- Master has hardhat-deploy integrated and the current branch (v1-audit-feedback) does not. 
- Steps causing the issue: We install the current branches npm packages, run gasCompare, then checkout to master and run gasCompare again. We now need to reinstall npm packages when checking out to master to make sure missing modules are installed.
> fix: reinstall npm packages when checking out to master circleci

- hardhat.config.js
Deployment can fail due to timeout error. This can happen if the RPC takes longer than 20 seconds(default) to respond. To fix this issue I have override the default timeout config for skale to 60 seconds.
fixes #819
> fix: increase network timeout

- contracts/Delegator.sol
- contracts/IDelegator.sol
- hardhat.config.js
- migrations/deploy_delegator.js
- migrations/src/postDeploymentSetup.js
- test/AssignCollectionsRandomly.js
- test/Delegator.js
- `getResult(name)`will now return a `Struct Value` that consists of `(power, collectionId, collectionName, result)` of the requested collection name.
- Updates the `IDelegator` interface so that this can be used by clients.
Deployment plan for staging([skale-testnet v3](https://staging-aware-chief-gianfar.explorer.staging-v3.skalenodes.com/)):
- Deployment script to deploy only the `Delegator.sol` contract 
- Grant `PAUSE_ROLE` to admin for Delegator in the postDeployment script
- `updateAddress(collectionManager, randomNoManager)` call this function with the previously deployed (currently live on staging oracle) Collection Manager  and RandomNoManger contract addresses. @SkandaBhat @SamAg19 
Resolves 
#985 
#986
#987
> feat: Delegator V2 that returns Values Struct of Collection 

- contracts/Core/BlockManager.sol
- contracts/Core/CollectionManager.sol
- contracts/Core/interface/IBlockManager.sol
- contracts/Core/interface/ICollectionManager.sol
- contracts/Core/storage/BlockStorage.sol
- contracts/Delegator.sol
- contracts/IDelegator.sol
- migrations/migrationHelpers.js
- test/Delegator.js
The current implementation does not store the timestamp at which the latest result of a particular collection is set. Clients require a timestamp to authenticate whether the reported result is the latest. 
fixes #989 
- When the block is confirmed, the mapping of the collection id to timestamp `latestResultTimestamp` is updated along with the result of the collection. 
- When we try to get the result through the collection manager from the `getResult` function, it will return power, result and timestamp
> feat: timestamp added and updated for each collection post block confirmation

- .github/workflows/ci.yml
- .github/workflows/release.yml
- yarn.lock
Current:
- remove reliance on semantic-release
- semantic-release creates a new tag and release 
- npm package release triggered on merges to `next` branch
New:
- create a tag and release it manually
- tag creation triggers npm package release
> CI updates to handle V2 release
